name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1
        with:
          token: ${{ secrets.SONARQUBE_TOKEN }}
          projectKey: <your_project_key>
          projectName: <your_project_name>
          organization: <your_organization_key>
